name: Build and Deploy WebAssembly Programs

on:
  push:
    branches:
      - main # 在 push 到 main 分支时触发
    paths-ignore:
      - "docs/**" # 忽略 docs 文件夹
      - "README.md" # 忽略根目录的 README 文件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # 初始化子模块

      # 2. 安装 Emscripten 环境
      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          echo "EMSDK=$PWD" >> $GITHUB_ENV
          echo "EMSDK_NODE=$PWD/node/14.18.2_64bit/bin/node" >> $GITHUB_ENV
          echo "PATH=$PWD:$PWD/upstream/emscripten:$PWD/node/14.18.2_64bit/bin:$PATH" >> $GITHUB_ENV

      # 3. 使用 Emscripten 编译所有 main.cpp 文件
      - name: Build WebAssembly
        run: |
          mkdir -p build
          cd build
          emcmake cmake ..
          cmake --build .

      # 4. 设置 Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 5. 生成 index.html
      - name: Generate Index
        run: |
          chmod +x generate_index.py
          ./generate_index.py

      # 6. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
